#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    sudo docker-compose start
fi

if [ "$1" == "stop" ]; then
    sudo docker-compose stop
fi

if [ "$1" == "update" ]; then    
    sudo docker-compose pull && sudo docker-compose up -d && sudo docker image prune -f
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && read -p "Enter your Origin domain (ex: mydomain.com) : " DOMAIN
  read -p "Enter your CDN domain (ex: cdn.mydomain.com) : " CDN_DOMAIN
  read -p "Enter your Email address for SSL certificate (ex: myemail@email.com) : " EMAIL \
  && cd /home; sudo git clone https://github.com/woosungchoi/docker-cdn-webserver \
  && sudo chown -R $USER /home/docker-cdn-webserver \
  && cd docker-cdn-webserver; git clone https://github.com/woosungchoi/my-image-cdn \
  && mv my-image-cdn/www . \
  && rm -rf my-image-cdn \
  && sudo chmod -R 777 www \
  && sed -i "s/<cdn_host>/$CDN_DOMAIN/g" nginx/conf.d/cdn-webserver.conf \
  && sed -i "s/<cdn_host>/$CDN_DOMAIN/g" nginx/conf.d/ssl-conf \
  && sed -i "s/<cdn_host>/$CDN_DOMAIN/g" docker-compose.yml \
  && sed -i "s/<cdn_host>/$CDN_DOMAIN/g" docker-compose.production.yml \
  && sed -i "s/<origin_host>/$DOMAIN/g" www/config.php \
  && sed -i "s/<origin_host>/$DOMAIN/g" nginx/conf.d/cdn-webserver.conf \
  && sed -i "s/<email>/$EMAIL/g" docker-compose.yml \
  && echo 'Setting timezone to Asia/Seoul...' \
  && sudo timedatectl set-timezone Asia/Seoul \
  && sudo mkdir -p /usr/share/nginx/html;
  echo 'Preparing docker-compose up' \
  && curl -sSLo nginx/conf.d/options-ssl-nginx https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf \
  && sudo chmod a+x dc \
  && sudo chmod a+x docker_upgrade_centos.sh \
  && echo 'Configuring cron...' \
  && echo "0 23 * * * docker start certbot >> /var/log/docker_cron.log 2>&1
5 23 * * * docker exec nginx nginx -s reload >> /var/log/docker_cron.log 2>&1
0 2 * * * /home/docker-cdn-webserver/docker-upgrade_centos.sh >> /var/log/docker_upgrade.log 2>&11
#10 4 * * * /usr/bin/find /home/docker-cdn-webserver/www -mindepth 2 -atime +10 -type f \( -iname \*.png -o -iname \*.jpg -o -iname \*.jpeg -o -iname \*.mp4 -o -iname \*.webm -o -iname \*.gif \) | xargs rm 1>/dev/null 2>/dev/null" >> cdncron \
  && sudo crontab cdncron; rm cdncron \
  && echo 'Installing Docker...' \
  && sudo yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine \
  && sudo dnf install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm \
  && sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo \
  && sudo dnf install -y docker-ce docker-ce-cli \
  && sudo systemctl start docker && sudo systemctl enable --now docker \
  && if [ ! -f /usr/bin/docker-compose ] ; then
        echo 'Installing Docker Compose...' \
        && COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4) \
        && sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose \
        && sudo chmod +x /usr/bin/docker-compose
        else echo 'Skip Installing Docker Compose'
     fi
  echo 'Installing SSL...' \
  && sudo docker-compose up \
  && sudo docker-compose down -v \
  && echo 'Starting Docker ...' \
  && sudo mv docker-compose.yml docker-compose.ssl.yml \
  && sudo mv docker-compose.production.yml docker-compose.yml \
  && sudo docker-compose up -d  \
  && echo 'Done! 🎉' \
  && echo 'by Lael and Woosung Choi' \
  && echo 'Below is a list of containers.'\
  && sudo docker-compose ps
fi
